algoritmo "antecessor_sucessor"
// Função : Calcula o antecessor e o sucessor de um número
// Autor :  Janaina
// Data : 17/03/2017
// Seção de Declarações 
var
   num1, antec, sucessor: inteiro
inicio
      escreva ("Digite um numero: ")
      leia (num1)
      antec <- num1-1
      sucessor <- num1+1
      escreval ("Antecessor é ", antec)
      escreval ("Sucessor é ", sucessor)
      
fimalgoritmo
