Algoritmo "elefante"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Janaina
// Descrição   : Música do elefantinho
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2017
Var

   cont: inteiro

Inicio

      escreval("1 elefante incomoda muita gente ")
      cont <- 2
      
      enquanto (cont<=30) faca
               se (cont%2=0) entao
                  escreval(cont, " elefantes incomodam muito mais")
               senao
                  escreval (cont, " elefantes incomodam muita gente")
               fimse

               cont <- cont+1
      fimenquanto


Fimalgoritmo