algoritmo "elefante"
// Função :
// Autor :
// Data : 17/03/2017
// Seção de Declarações 
var
   contador: inteiro
inicio

      contador <- contador+1
      se contador = 1 entao
         escreva (contador, "Incomoda muita gente)
      senao
         se contador % 2 = 0 entao
            escreva (contador, "Incomodam muita gente)
         senao
            escreva (contador, "Incomodam muito mais")
      fimse

fimalgoritmo
