Algoritmo "tabuada do 1 ao 10"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/03/2017
Var

x, y : inteiro


Inicio

     repita
         x <- x+1
         
         Escreval ("Tabuada do número", x)

         enquanto (y < 10) faca
         y <- y+1
                  Escreval (x, " x ", y, " = ", x*y)
         fimenquanto


      ate (x = 10)

Fimalgoritmo