Algoritmo "tabuada"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Exercicio   : Tabuada do 5 com a quantidade de operadores que
// o usuário forneceu


Var

cont, qtde : inteiro


Inicio

      escreval ("***** Tabuado do número 5 *****")
      escreval("")
      escreva ("Digite a quantidade de operadores: ")

      leia(qtde)
      
      enquanto (cont < qtde) faca
            cont <- cont+1
            Escreval ("5 x ", cont, " = ", cont * 5)
      fimenquanto


Fimalgoritmo